


import React, { useState, useEffect } from 'react';
import { ChecklistTemplate, ChecklistItemBase, QuestionType } from '../../types';
import Card from '../shared/Card';
import Button from '../shared/Button';
import { Plus, Trash2, FilePlus, Save } from 'lucide-react';

interface TemplateEditorViewProps {
  templates: ChecklistTemplate[];
  onSave: (template: ChecklistTemplate) => void;
}

const NEW_TEMPLATE: ChecklistTemplate = {
  id: '',
  title: 'New Checklist Template',
  items: [],
};

const TemplateEditorView: React.FC<TemplateEditorViewProps> = ({ templates, onSave }) => {
  const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(null);
  const [activeTemplate, setActiveTemplate] = useState<ChecklistTemplate>(NEW_TEMPLATE);
  const isNew = !selectedTemplateId;

  useEffect(() => {
    localStorage.setItem('templateDraftActive', '1');
    const draftRaw = localStorage.getItem('templateEditorDraft');
    if (draftRaw) {
      try {
        const draft = JSON.parse(draftRaw) as { selectedTemplateId: string | null; activeTemplate: ChecklistTemplate };
        if (draft && draft.activeTemplate) {
          setSelectedTemplateId(draft.selectedTemplateId);
          setActiveTemplate(draft.activeTemplate);
        }
      } catch {}
    }
    return () => {
      localStorage.removeItem('templateDraftActive');
    };
  }, []);

  useEffect(() => {
    if (selectedTemplateId) {
      const found = templates.find(t => t.id === selectedTemplateId);
      setActiveTemplate(found ? { ...found } : { ...NEW_TEMPLATE });
    } else {
      setActiveTemplate({ ...NEW_TEMPLATE });
    }
  }, [selectedTemplateId, templates]);

  useEffect(() => {
    const payload = JSON.stringify({ selectedTemplateId, activeTemplate });
    try {
      localStorage.setItem('templateEditorDraft', payload);
    } catch {}
  }, [selectedTemplateId, activeTemplate]);
  const handleSelectTemplate = (id: string) => {
    setSelectedTemplateId(id);
  };

  const handleCreateNew = () => {
    setSelectedTemplateId(null);
    setActiveTemplate({ ...NEW_TEMPLATE, id: '' });
  };
  
  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setActiveTemplate(prev => ({ ...prev, title: e.target.value }));
  };

  const handleItemChange = (index: number, field: keyof ChecklistItemBase, value: any) => {
    setActiveTemplate(prev => {
        const newItems = [...prev.items];
        const currentItem = { ...newItems[index], [field]: value };
        newItems[index] = currentItem;
        return { ...prev, items: newItems };
    });
  };

  const handleAddItem = () => {
      const newItem: ChecklistItemBase = {
          id: `item-${Date.now()}`,
          question: '',
          type: 'yes-no',
          required: true,
          minPhotos: 0
      };
      setActiveTemplate(prev => ({ ...prev, items: [...prev.items, newItem] }));
  };
  
  const handleRemoveItem = (index: number) => {
    setActiveTemplate(prev => ({...prev, items: prev.items.filter((_, i) => i !== index)}));
  };

  const handleSaveTemplate = () => {
    if (!activeTemplate.title.trim()) {
        alert("Template title cannot be empty.");
        return;
    }
    // FIX: Do not generate a client-side ID. The parent component will handle this
    // to ensure a proper UUID is generated by the database for new templates.
    const templateToSave = { ...activeTemplate };
    onSave(templateToSave);
    // Clear draft on successful save invocation
    localStorage.removeItem('templateEditorDraft');
    localStorage.removeItem('templateDraftActive');
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 h-full">
      <Card className="lg:col-span-1 flex flex-col">
        <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-bold text-neutral">Templates</h2>
            <Button onClick={handleCreateNew} variant="secondary" className="px-2 py-1 text-xs">
                <FilePlus size={14} className="mr-1" /> New
            </Button>
        </div>
        <ul className="space-y-2 overflow-y-auto">
          {templates.map(template => (
            <li 
              key={template.id}
              onClick={() => handleSelectTemplate(template.id)}
              className={`p-3 rounded-lg cursor-pointer transition-colors ${selectedTemplateId === template.id ? 'bg-primary text-white' : 'hover:bg-base-200'}`}
            >
              {template.title}
            </li>
          ))}
        </ul>
      </Card>
      
      <Card className="lg:col-span-2 flex flex-col">
          <div className="flex-grow overflow-y-auto pr-2">
            <h2 className="text-xl font-bold text-neutral mb-4">{isNew ? 'Create New Template' : 'Edit Template'}</h2>
            <div className="space-y-6">
                <div>
                    <label htmlFor="templateTitle" className="block text-sm font-medium text-gray-700">Template Title</label>
                    <input 
                        type="text" 
                        id="templateTitle"
                        value={activeTemplate.title}
                        onChange={handleTitleChange}
                        className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-primary focus:border-primary"
                    />
                </div>
                <div>
                    <h3 className="text-lg font-semibold text-gray-800 mb-3">Questions</h3>
                    <div className="space-y-4">
                        {activeTemplate.items.map((item, index) => (
                            <div key={item.id} className="p-4 border rounded-lg bg-base-200/60 shadow-sm space-y-3">
                                {/* Row 1: Question Text and Delete Button */}
                                <div className="flex items-center space-x-3">
                                    <span className="font-bold text-primary text-lg">{index + 1}.</span>
                                    <input
                                        type="text"
                                        placeholder="Enter question text..."
                                        value={item.question}
                                        onChange={(e) => handleItemChange(index, 'question', e.target.value)}
                                        className="flex-grow px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary"
                                    />
                                    <button onClick={() => handleRemoveItem(index)} className="p-2 text-gray-500 hover:text-error rounded-full hover:bg-red-100 transition-colors">
                                        <Trash2 size={18} />
                                    </button>
                                </div>

                                {/* Row 2: Options */}
                                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-4 pl-9 pt-2">
                                    {/* Answer Type */}
                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-1">Answer Type</label>
                                        <select
                                            value={item.type}
                                            onChange={(e) => handleItemChange(index, 'type', e.target.value as QuestionType)}
                                            className="w-full px-2 py-1.5 border border-gray-300 bg-white rounded-md text-sm shadow-sm focus:ring-primary focus:border-primary"
                                        >
                                            <option value="yes-no">Yes/No</option>
                                            <option value="text">Text</option>
                                            <option value="number">Number</option>
                                            <option value="photo">Photo</option>
                                            <option value="signature">Signature</option>
                                        </select>
                                    </div>
                                    
                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-1">Minimum Photos</label>
                                        <input
                                            type="number"
                                            min="0"
                                            value={item.minPhotos || 0}
                                            onChange={(e) => handleItemChange(index, 'minPhotos', parseInt(e.target.value, 10) || 0)}
                                            className="w-full px-2 py-1.5 border border-gray-300 rounded-md text-sm shadow-sm focus:ring-primary focus:border-primary"
                                        />
                                    </div>

                                    {(item.type === 'photo' || (item.minPhotos || 0) > 0) && (
                                      <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-1">Photo Source</label>
                                        <select
                                          value={item.photoSource || 'live'}
                                          onChange={(e) => handleItemChange(index, 'photoSource', e.target.value)}
                                          className="w-full px-2 py-1.5 border border-gray-300 bg-white rounded-md text-sm shadow-sm focus:ring-primary focus:border-primary"
                                        >
                                          <option value="live">Live Camera</option>
                                          <option value="upload">Upload</option>
                                        </select>
                                      </div>
                                    )}

                                    {/* Mandatory Options */}
                                    <div className="col-span-1 lg:col-span-1 flex items-end space-x-6 flex-wrap">
                                        <label className="flex items-center text-sm font-medium cursor-pointer pt-2">
                                            <input
                                                type="checkbox"
                                                checked={item.required}
                                                onChange={(e) => handleItemChange(index, 'required', e.target.checked)}
                                                className="h-4 w-4 text-primary focus:ring-primary-focus border-gray-300 rounded"
                                            />
                                            <span className="ml-2 text-gray-700">Mandatory Question</span>
                                        </label>

                                        <label className="flex items-center text-sm font-medium cursor-pointer pt-2">
                                            <input
                                                type="checkbox"
                                                checked={item.requireNote || false}
                                                onChange={(e) => handleItemChange(index, 'requireNote', e.target.checked)}
                                                className="h-4 w-4 text-primary focus:ring-primary-focus border-gray-300 rounded"
                                            />
                                            <span className="ml-2 text-gray-700">Mandatory Note</span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                    <Button onClick={handleAddItem} variant="secondary" className="w-full mt-4">
                        <Plus size={16} className="mr-2" /> Add Question
                    </Button>
                </div>
            </div>
          </div>
          <div className="pt-4 mt-4 border-t flex justify-end">
                <Button onClick={handleSaveTemplate}>
                    <Save size={18} className="mr-2"/> Save Template
                </Button>
            </div>
      </Card>
    </div>
  );
};

export default TemplateEditorView;
